require('basic')
require('cursor')
require('colorscheme')
require('keybindings')
require('plugins')
-- 插件配置
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.nvim-treesitter")
--require("lsp.setup")
require("plugin-config.dashboard")
