local map = vim.api.nvim_set_keymap
vim.g.mapleader = " "
vim.g.maplocalleader = " "
-- 复用 opt 参数
local opt = {noremap= true, silent = true }
local opt1 = {noremap= true, silent = false }


map("","e","j",opt)
map("","j","e",opt)

map("","h","n",opt)
map("","H","N",opt)
map("","n","h",opt)

map("","u","k",opt)

map("n","l","u",opt)
map("n","L","<C-r>",opt)

map("","i","l",opt)

map("","k","i",opt)
map("","K","I",opt)

--map("n","J","E",opt)

map("n","U","5k",opt)
map("n","E","5j",opt)

map("","N","0",opt)
map("","I","$",opt)

map("","W","5w",opt)
map("","B","5b",opt)

map("","<C-U>","5<C-y>",opt)
map("","<C-E>","5<C-e>",opt)

map("",   "[a<Leader>",   "1k",opt)
map("",   "[r<LEADER>",   "2k",opt)
map("",   "[s<LEADER>",   "3k",opt)
map("",   "[t<LEADER>",   "4k",opt)
map("",   "[d<LEADER>",   "5k",opt)
map("",   "[h<LEADER>",   "6k",opt)
map("",   "[n<LEADER>",   "7k",opt)
map("",   "[e<LEADER>",   "8k",opt)
map("",   "[i<LEADER>",   "9k",opt)
map("",  "[ao<LEADER>",  "10k",opt)
map("",  "[aa<LEADER>",  "11k",opt)
map("",  "[ar<LEADER>",  "12k",opt)
map("",  "[as<LEADER>",  "13k",opt)
map("",  "[at<LEADER>",  "14k",opt)
map("",  "[ad<LEADER>",  "15k",opt)
map("",  "[ah<LEADER>",  "16k",opt)
map("",  "[an<LEADER>",  "17k",opt)
map("",  "[ae<LEADER>",  "18k",opt)
map("",  "[ai<LEADER>",  "19k",opt)
map("",  "[ro<LEADER>",  "20k",opt)
map("",  "[ra<LEADER>",  "21k",opt)
map("",  "[rr<LEADER>",  "22k",opt)
map("",  "[rs<LEADER>",  "23k",opt)
map("",  "[rt<LEADER>",  "24k",opt)
map("",  "[rd<LEADER>",  "25k",opt)
map("",  "[rh<LEADER>",  "26k",opt)
map("",  "[rn<LEADER>",  "27k",opt)
map("",  "[re<LEADER>",  "28k",opt)
map("",  "[ri<LEADER>",  "29k",opt)
map("",  "[so<LEADER>",  "30k",opt)
map("",  "[sa<LEADER>",  "31k",opt)
map("",  "[sr<LEADER>",  "32k",opt)
map("",  "[ss<LEADER>",  "33k",opt)
map("",  "[st<LEADER>",  "34k",opt)
map("",  "[sd<LEADER>",  "35k",opt)
map("",  "[sh<LEADER>",  "36k",opt)
map("",  "[sn<LEADER>",  "37k",opt)
map("",  "[se<LEADER>",  "38k",opt)
map("",  "[si<LEADER>",  "39k",opt)
map("",  "[to<LEADER>",  "40k",opt)
map("",  "[ta<LEADER>",  "41k",opt)
map("",  "[tr<LEADER>",  "42k",opt)
map("",  "[ts<LEADER>",  "43k",opt)
map("",  "[tt<LEADER>",  "44k",opt)
map("",  "[td<LEADER>",  "45k",opt)
map("",  "[th<LEADER>",  "46k",opt)
map("",  "[tn<LEADER>",  "47k",opt)
map("",  "[te<LEADER>",  "48k",opt)
map("",  "[ti<LEADER>",  "49k",opt)
map("",  "[do<LEADER>",  "50k",opt)
map("",  "[da<LEADER>",  "51k",opt)
map("",  "[dr<LEADER>",  "52k",opt)
map("",  "[ds<LEADER>",  "53k",opt)
map("",  "[dt<LEADER>",  "54k",opt)
map("",  "[dd<LEADER>",  "55k",opt)
map("",  "[dh<LEADER>",  "56k",opt)
map("",  "[dn<LEADER>",  "57k",opt)
map("",  "[de<LEADER>",  "58k",opt)
map("",  "[di<LEADER>",  "59k",opt)
map("",  "[ho<LEADER>",  "60k",opt)
map("",  "[ha<LEADER>",  "61k",opt)
map("",  "[hr<LEADER>",  "62k",opt)
map("",  "[hs<LEADER>",  "63k",opt)
map("",  "[ht<LEADER>",  "64k",opt)
map("",  "[hd<LEADER>",  "65k",opt)
map("",  "[hh<LEADER>",  "66k",opt)
map("",  "[hn<LEADER>",  "67k",opt)
map("",  "[he<LEADER>",  "68k",opt)
map("",  "[hi<LEADER>",  "69k",opt)
map("",  "[no<LEADER>",  "70k",opt)
map("",  "[na<LEADER>",  "71k",opt)
map("",  "[nr<LEADER>",  "72k",opt)
map("",  "[ns<LEADER>",  "73k",opt)
map("",  "[nt<LEADER>",  "74k",opt)
map("",  "[nd<LEADER>",  "75k",opt)
map("",  "[nh<LEADER>",  "76k",opt)
map("",  "[nn<LEADER>",  "77k",opt)
map("",  "[ne<LEADER>",  "78k",opt)
map("",  "[ni<LEADER>",  "79k",opt)
map("",  "[eo<LEADER>",  "80k",opt)
map("",  "[ea<LEADER>",  "81k",opt)
map("",  "[er<LEADER>",  "82k",opt)
map("",  "[es<LEADER>",  "83k",opt)
map("",  "[et<LEADER>",  "84k",opt)
map("",  "[ed<LEADER>",  "85k",opt)
map("",  "[eh<LEADER>",  "86k",opt)
map("",  "[en<LEADER>",  "87k",opt)
map("",  "[ee<LEADER>",  "88k",opt)
map("",  "[ei<LEADER>",  "89k",opt)
map("",  "[io<LEADER>",  "90k",opt)
map("",  "[ia<LEADER>",  "91k",opt)
map("",  "[ir<LEADER>",  "92k",opt)
map("",  "[is<LEADER>",  "93k",opt)
map("",  "[it<LEADER>",  "94k",opt)
map("",  "[id<LEADER>",  "95k",opt)
map("",  "[ih<LEADER>",  "96k",opt)
map("",  "[in<LEADER>",  "97k",opt)
map("",  "[ie<LEADER>",  "98k",opt)
map("",  "[ii<LEADER>",  "99k",opt)
map("", "[aoo<LEADER>", "100k",opt)
map("", "[aoa<LEADER>", "101k",opt)
map("", "[aor<LEADER>", "102k",opt)
map("", "[aos<LEADER>", "103k",opt)
map("", "[aot<LEADER>", "104k",opt)
map("", "[aod<LEADER>", "105k",opt)
map("", "[aoh<LEADER>", "106k",opt)
map("", "[aon<LEADER>", "107k",opt)
map("", "[aoe<LEADER>", "108k",opt)
map("", "[aoi<LEADER>", "109k",opt)
map("", "[aao<LEADER>", "110k",opt)
map("", "[aaa<LEADER>", "111k",opt)
map("", "[aar<LEADER>", "112k",opt)
map("", "[aas<LEADER>", "113k",opt)
map("", "[aat<LEADER>", "114k",opt)
map("", "[aad<LEADER>", "115k",opt)
map("", "[aah<LEADER>", "116k",opt)
map("", "[aan<LEADER>", "117k",opt)
map("", "[aae<LEADER>", "118k",opt)
map("", "[aai<LEADER>", "119k",opt)
map("", "[aro<LEADER>", "120k",opt)
map("", "[ara<LEADER>", "121k",opt)
map("", "[arr<LEADER>", "122k",opt)
map("", "[ars<LEADER>", "123k",opt)
map("", "[art<LEADER>", "124k",opt)
map("", "[ard<LEADER>", "125k",opt)
map("", "[arh<LEADER>", "126k",opt)
map("", "[arn<LEADER>", "127k",opt)
map("", "[are<LEADER>", "128k",opt)
map("", "[ari<LEADER>", "129k",opt)
map("", "[aso<LEADER>", "130k",opt)
map("", "[asa<LEADER>", "131k",opt)
map("", "[asr<LEADER>", "132k",opt)
map("", "[ass<LEADER>", "133k",opt)
map("", "[ast<LEADER>", "134k",opt)
map("", "[asd<LEADER>", "135k",opt)
map("", "[ash<LEADER>", "136k",opt)
map("", "[asn<LEADER>", "137k",opt)
map("", "[ase<LEADER>", "138k",opt)
map("", "[asi<LEADER>", "139k",opt)
map("", "[ato<LEADER>", "140k",opt)
map("", "[ata<LEADER>", "141k",opt)
map("", "[atr<LEADER>", "142k",opt)
map("", "[ats<LEADER>", "143k",opt)
map("", "[att<LEADER>", "144k",opt)
map("", "[atd<LEADER>", "145k",opt)
map("", "[ath<LEADER>", "146k",opt)
map("", "[atn<LEADER>", "147k",opt)
map("", "[ate<LEADER>", "148k",opt)
map("", "[ati<LEADER>", "149k",opt)
map("", "[ado<LEADER>", "150k",opt)
map("", "[ada<LEADER>", "151k",opt)
map("", "[adr<LEADER>", "152k",opt)
map("", "[ads<LEADER>", "153k",opt)
map("", "[adt<LEADER>", "154k",opt)
map("", "[add<LEADER>", "155k",opt)
map("", "[adh<LEADER>", "156k",opt)
map("", "[adn<LEADER>", "157k",opt)
map("", "[ade<LEADER>", "158k",opt)
map("", "[adi<LEADER>", "159k",opt)
map("", "[aho<LEADER>", "160k",opt)
map("", "[aha<LEADER>", "161k",opt)
map("", "[ahr<LEADER>", "162k",opt)
map("", "[ahs<LEADER>", "163k",opt)
map("", "[aht<LEADER>", "164k",opt)
map("", "[ahd<LEADER>", "165k",opt)
map("", "[ahh<LEADER>", "166k",opt)
map("", "[ahn<LEADER>", "167k",opt)
map("", "[ahe<LEADER>", "168k",opt)
map("", "[ahi<LEADER>", "169k",opt)
map("", "[ano<LEADER>", "170k",opt)
map("", "[ana<LEADER>", "171k",opt)
map("", "[anr<LEADER>", "172k",opt)
map("", "[ans<LEADER>", "173k",opt)
map("", "[ant<LEADER>", "174k",opt)
map("", "[and<LEADER>", "175k",opt)
map("", "[anh<LEADER>", "176k",opt)
map("", "[ann<LEADER>", "177k",opt)
map("", "[ane<LEADER>", "178k",opt)
map("", "[ani<LEADER>", "179k",opt)
map("", "[aeo<LEADER>", "180k",opt)
map("", "[aea<LEADER>", "181k",opt)
map("", "[aer<LEADER>", "182k",opt)
map("", "[aes<LEADER>", "183k",opt)
map("", "[aet<LEADER>", "184k",opt)
map("", "[aed<LEADER>", "185k",opt)
map("", "[aeh<LEADER>", "186k",opt)
map("", "[aen<LEADER>", "187k",opt)
map("", "[aee<LEADER>", "188k",opt)
map("", "[aei<LEADER>", "189k",opt)
map("", "[aio<LEADER>", "190k",opt)
map("", "[aia<LEADER>", "191k",opt)
map("", "[air<LEADER>", "192k",opt)
map("", "[ais<LEADER>", "193k",opt)
map("", "[ait<LEADER>", "194k",opt)
map("", "[aid<LEADER>", "195k",opt)
map("", "[aih<LEADER>", "196k",opt)
map("", "[ain<LEADER>", "197k",opt)
map("", "[aie<LEADER>", "198k",opt)
map("", "[aii<LEADER>", "199k",opt)

map("",   "'a<LEADER>",   "1j",opt)
map("",   "'r<LEADER>",   "2j",opt)
map("",   "'s<LEADER>",   "3j",opt)
map("",   "'t<LEADER>",   "4j",opt)
map("",   "'d<LEADER>",   "5j",opt)
map("",   "'h<LEADER>",   "6j",opt)
map("",   "'n<LEADER>",   "7j",opt)
map("",   "'e<LEADER>",   "8j",opt)
map("",   "'i<LEADER>",   "9j",opt)
map("",  "'ao<LEADER>",  "10j",opt)
map("",  "'aa<LEADER>",  "11j",opt)
map("",  "'ar<LEADER>",  "12j",opt)
map("",  "'as<LEADER>",  "13j",opt)
map("",  "'at<LEADER>",  "14j",opt)
map("",  "'ad<LEADER>",  "15j",opt)
map("",  "'ah<LEADER>",  "16j",opt)
map("",  "'an<LEADER>",  "17j",opt)
map("",  "'ae<LEADER>",  "18j",opt)
map("",  "'ai<LEADER>",  "19j",opt)
map("",  "'ro<LEADER>",  "20j",opt)
map("",  "'ra<LEADER>",  "21j",opt)
map("",  "'rr<LEADER>",  "22j",opt)
map("",  "'rs<LEADER>",  "23j",opt)
map("",  "'rt<LEADER>",  "24j",opt)
map("",  "'rd<LEADER>",  "25j",opt)
map("",  "'rh<LEADER>",  "26j",opt)
map("",  "'rn<LEADER>",  "27j",opt)
map("",  "'re<LEADER>",  "28j",opt)
map("",  "'ri<LEADER>",  "29j",opt)
map("",  "'so<LEADER>",  "30j",opt)
map("",  "'sa<LEADER>",  "31j",opt)
map("",  "'sr<LEADER>",  "32j",opt)
map("",  "'ss<LEADER>",  "33j",opt)
map("",  "'st<LEADER>",  "34j",opt)
map("",  "'sd<LEADER>",  "35j",opt)
map("",  "'sh<LEADER>",  "36j",opt)
map("",  "'sn<LEADER>",  "37j",opt)
map("",  "'se<LEADER>",  "38j",opt)
map("",  "'si<LEADER>",  "39j",opt)
map("",  "'to<LEADER>",  "40j",opt)
map("",  "'ta<LEADER>",  "41j",opt)
map("",  "'tr<LEADER>",  "42j",opt)
map("",  "'ts<LEADER>",  "43j",opt)
map("",  "'tt<LEADER>",  "44j",opt)
map("",  "'td<LEADER>",  "45j",opt)
map("",  "'th<LEADER>",  "46j",opt)
map("",  "'tn<LEADER>",  "47j",opt)
map("",  "'te<LEADER>",  "48j",opt)
map("",  "'ti<LEADER>",  "49j",opt)
map("",  "'do<LEADER>",  "50j",opt)
map("",  "'da<LEADER>",  "51j",opt)
map("",  "'dr<LEADER>",  "52j",opt)
map("",  "'ds<LEADER>",  "53j",opt)
map("",  "'dt<LEADER>",  "54j",opt)
map("",  "'dd<LEADER>",  "55j",opt)
map("",  "'dh<LEADER>",  "56j",opt)
map("",  "'dn<LEADER>",  "57j",opt)
map("",  "'de<LEADER>",  "58j",opt)
map("",  "'di<LEADER>",  "59j",opt)
map("",  "'ho<LEADER>",  "60j",opt)
map("",  "'ha<LEADER>",  "61j",opt)
map("",  "'hr<LEADER>",  "62j",opt)
map("",  "'hs<LEADER>",  "63j",opt)
map("",  "'ht<LEADER>",  "64j",opt)
map("",  "'hd<LEADER>",  "65j",opt)
map("",  "'hh<LEADER>",  "66j",opt)
map("",  "'hn<LEADER>",  "67j",opt)
map("",  "'he<LEADER>",  "68j",opt)
map("",  "'hi<LEADER>",  "69j",opt)
map("",  "'no<LEADER>",  "70j",opt)
map("",  "'na<LEADER>",  "71j",opt)
map("",  "'nr<LEADER>",  "72j",opt)
map("",  "'ns<LEADER>",  "73j",opt)
map("",  "'nt<LEADER>",  "74j",opt)
map("",  "'nd<LEADER>",  "75j",opt)
map("",  "'nh<LEADER>",  "76j",opt)
map("",  "'nn<LEADER>",  "77j",opt)
map("",  "'ne<LEADER>",  "78j",opt)
map("",  "'ni<LEADER>",  "79j",opt)
map("",  "'eo<LEADER>",  "80j",opt)
map("",  "'ea<LEADER>",  "81j",opt)
map("",  "'er<LEADER>",  "82j",opt)
map("",  "'es<LEADER>",  "83j",opt)
map("",  "'et<LEADER>",  "84j",opt)
map("",  "'ed<LEADER>",  "85j",opt)
map("",  "'eh<LEADER>",  "86j",opt)
map("",  "'en<LEADER>",  "87j",opt)
map("",  "'ee<LEADER>",  "88j",opt)
map("",  "'ei<LEADER>",  "89j",opt)
map("",  "'io<LEADER>",  "90j",opt)
map("",  "'ia<LEADER>",  "91j",opt)
map("",  "'ir<LEADER>",  "92j",opt)
map("",  "'is<LEADER>",  "93j",opt)
map("",  "'it<LEADER>",  "94j",opt)
map("",  "'id<LEADER>",  "95j",opt)
map("",  "'ih<LEADER>",  "96j",opt)
map("",  "'in<LEADER>",  "97j",opt)
map("",  "'ie<LEADER>",  "98j",opt)
map("",  "'ii<LEADER>",  "99j",opt)
map("", "'aoo<LEADER>", "100j",opt)
map("", "'aoa<LEADER>", "101j",opt)
map("", "'aor<LEADER>", "102j",opt)
map("", "'aos<LEADER>", "103j",opt)
map("", "'aot<LEADER>", "104j",opt)
map("", "'aod<LEADER>", "105j",opt)
map("", "'aoh<LEADER>", "106j",opt)
map("", "'aon<LEADER>", "107j",opt)
map("", "'aoe<LEADER>", "108j",opt)
map("", "'aoi<LEADER>", "109j",opt)
map("", "'aao<LEADER>", "110j",opt)
map("", "'aaa<LEADER>", "111j",opt)
map("", "'aar<LEADER>", "112j",opt)
map("", "'aas<LEADER>", "113j",opt)
map("", "'aat<LEADER>", "114j",opt)
map("", "'aad<LEADER>", "115j",opt)
map("", "'aah<LEADER>", "116j",opt)
map("", "'aan<LEADER>", "117j",opt)
map("", "'aae<LEADER>", "118j",opt)
map("", "'aai<LEADER>", "119j",opt)
map("", "'aro<LEADER>", "120j",opt)
map("", "'ara<LEADER>", "121j",opt)
map("", "'arr<LEADER>", "122j",opt)
map("", "'ars<LEADER>", "123j",opt)
map("", "'art<LEADER>", "124j",opt)
map("", "'ard<LEADER>", "125j",opt)
map("", "'arh<LEADER>", "126j",opt)
map("", "'arn<LEADER>", "127j",opt)
map("", "'are<LEADER>", "128j",opt)
map("", "'ari<LEADER>", "129j",opt)
map("", "'aso<LEADER>", "130j",opt)
map("", "'asa<LEADER>", "131j",opt)
map("", "'asr<LEADER>", "132j",opt)
map("", "'ass<LEADER>", "133j",opt)
map("", "'ast<LEADER>", "134j",opt)
map("", "'asd<LEADER>", "135j",opt)
map("", "'ash<LEADER>", "136j",opt)
map("", "'asn<LEADER>", "137j",opt)
map("", "'ase<LEADER>", "138j",opt)
map("", "'asi<LEADER>", "139j",opt)
map("", "'ato<LEADER>", "140j",opt)
map("", "'ata<LEADER>", "141j",opt)
map("", "'atr<LEADER>", "142j",opt)
map("", "'ats<LEADER>", "143j",opt)
map("", "'att<LEADER>", "144j",opt)
map("", "'atd<LEADER>", "145j",opt)
map("", "'ath<LEADER>", "146j",opt)
map("", "'atn<LEADER>", "147j",opt)
map("", "'ate<LEADER>", "148j",opt)
map("", "'ati<LEADER>", "149j",opt)
map("", "'ado<LEADER>", "150j",opt)
map("", "'ada<LEADER>", "151j",opt)
map("", "'adr<LEADER>", "152j",opt)
map("", "'ads<LEADER>", "153j",opt)
map("", "'adt<LEADER>", "154j",opt)
map("", "'add<LEADER>", "155j",opt)
map("", "'adh<LEADER>", "156j",opt)
map("", "'adn<LEADER>", "157j",opt)
map("", "'ade<LEADER>", "158j",opt)
map("", "'adi<LEADER>", "159j",opt)
map("", "'aho<LEADER>", "160j",opt)
map("", "'aha<LEADER>", "161j",opt)
map("", "'ahr<LEADER>", "162j",opt)
map("", "'ahs<LEADER>", "163j",opt)
map("", "'aht<LEADER>", "164j",opt)
map("", "'ahd<LEADER>", "165j",opt)
map("", "'ahh<LEADER>", "166j",opt)
map("", "'ahn<LEADER>", "167j",opt)
map("", "'ahe<LEADER>", "168j",opt)
map("", "'ahi<LEADER>", "169j",opt)
map("", "'ano<LEADER>", "170j",opt)
map("", "'ana<LEADER>", "171j",opt)
map("", "'anr<LEADER>", "172j",opt)
map("", "'ans<LEADER>", "173j",opt)
map("", "'ant<LEADER>", "174j",opt)
map("", "'and<LEADER>", "175j",opt)
map("", "'anh<LEADER>", "176j",opt)
map("", "'ann<LEADER>", "177j",opt)
map("", "'ane<LEADER>", "178j",opt)
map("", "'ani<LEADER>", "179j",opt)
map("", "'aeo<LEADER>", "180j",opt)
map("", "'aea<LEADER>", "181j",opt)
map("", "'aer<LEADER>", "182j",opt)
map("", "'aes<LEADER>", "183j",opt)
map("", "'aet<LEADER>", "184j",opt)
map("", "'aed<LEADER>", "185j",opt)
map("", "'aeh<LEADER>", "186j",opt)
map("", "'aen<LEADER>", "187j",opt)
map("", "'aee<LEADER>", "188j",opt)
map("", "'aei<LEADER>", "189j",opt)
map("", "'aio<LEADER>", "190j",opt)
map("", "'aia<LEADER>", "191j",opt)
map("", "'air<LEADER>", "192j",opt)
map("", "'ais<LEADER>", "193j",opt)
map("", "'ait<LEADER>", "194j",opt)
map("", "'aid<LEADER>", "195j",opt)
map("", "'aih<LEADER>", "196j",opt)
map("", "'ain<LEADER>", "197j",opt)
map("", "'aie<LEADER>", "198j",opt)
map("", "'aii<LEADER>", "199j",opt)





map("c","<A-h>","<Home>",opt1)
map("c","<A-o>","<End>",opt1)
map("c","<A-w>","<Up>",opt1)
map("c","<A-r>","<Down>",opt1)
map("c","<A-a>","<Left>",opt1)
map("c","<A-s>","<Right>",opt1)
map("c","<A-A>","<S-Left>",opt1)
map("c","<A-S>","<S-Right>",opt1)
